version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
      - ./home:/home
    ports:
      - 5432:5432
